name: Snyk_SCA_Scan
on: [push]
jobs:
  Snyk_SCA_Scan:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v1
    - name: Snyk SCA Scanning
      run: |
        echo "----------Download Latest Snyk CLI-----------"
        curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.1159.0/snyk-linux"
        chmod +x snyk
        ls -lrt
        echo "----------Authenticating Snyk-----------"
        ./snyk auth ${{secrets.SNYK_TOKEN}}
        echo "----------Snyk Monitor-----------"
        ./snyk monitor --all-projects
        echo "----------Snyk Scanning and failing build in CI-----------"
        ./snyk test --all-projects --severity-threshold=high --fail-on=upgradable

